services:
  - docker

env:
  - BRANCH=${BRANCH:-ce} OPTIMIZER_ORTOOLS_VERSION=dev ORTOOLS_VERSION=v7.0

script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USERNAME" --password-stdin ${REGISTRY}
  - export OWNER=$(echo ${TRAVIS_REPO_SLUG} | sed "s/\/.*//")
  - export IMAGE_NAME=${REGISTRY}mapotempo-${BRANCH}/optimizer-ortools:${OWNER:-latest}
  - sudo apt-get -y install git wget pkg-config build-essential cmake autoconf libtool zlib1g-dev lsb-release > /dev/null
  - docker build --build-arg OPTIMIZER_ORTOOLS_VERSION=${OPTIMIZER_ORTOOLS_VERSION} --build-arg ORTOOLS_VERSION=${ORTOOLS_VERSION} --build-arg BRANCH=${BRANCH} -f ./Dockerfile -t ${IMAGE_NAME} .
  - docker push ${IMAGE_NAME}
